services:
  - type: web
    name: relaxify-server
    runtime: node
    buildCommand: cd server && npm install && pip install -U yt-dlp
    startCommand: cd /opt/render/project/src/server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: YOUTUBE_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: JWT_SECRET
        sync: false
